"""
3D visualization that combines SCI ratio and MSCC curve into one anatomical-style cylinder.

Input per subject (generated by the two batch scripts):
- sci_ratio_by_slice.csv
- mscc_by_slice.csv
"""

import argparse
import logging
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import LightSource
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from scipy.ndimage import gaussian_filter1d


def _resolve_first_existing(subject_path: Path, candidates: list[str]) -> Path | None:
    for name in candidates:
        p = subject_path / name
        if p.exists():
            return p
    return None


def create_3d_visualization(subject_path: Path, output_path: Path, subject_id: str) -> None:
    # Support new canonical names and legacy names.
    sci_csv = _resolve_first_existing(subject_path, ["sci_ratio_by_slice.csv", "injury_ratios_per_slice.csv"])
    mscc_csv = _resolve_first_existing(subject_path, ["mscc_by_slice.csv", "mscc_analysis.csv"])
    if sci_csv is None or mscc_csv is None:
        logging.warning("Missing input CSV(s) for %s", subject_id)
        return

    df_sci = pd.read_csv(sci_csv)
    df_mscc = pd.read_csv(mscc_csv)
    n_points = min(len(df_sci), len(df_mscc))
    if n_points < 2:
        logging.warning("Not enough points for %s", subject_id)
        return

    ratios = gaussian_filter1d(df_sci["Ratio"].values[:n_points], sigma=1.0)
    mscc_vals = gaussian_filter1d(df_mscc["MSCC_Smoothed"].values[:n_points], sigma=5.0)
    segments = df_sci["Segment"].values[:n_points]

    num_z = n_points
    num_theta = 180
    theta = np.linspace(0, 2 * np.pi, num_theta)
    z_phys = np.linspace(0, 40, num_z)[::-1]
    th, z = np.meshgrid(theta, z_phys)

    def anatomical_contour(theta_val):
        x = 1.6 * np.cos(theta_val)
        y = 1.1 * np.sin(theta_val)
        indent_top = 0.38 * np.maximum(0, np.sin(theta_val)) ** 16
        indent_bottom = 0.12 * np.maximum(0, -np.sin(theta_val)) ** 6
        r_mod = 1.0 - indent_top - indent_bottom
        return x * r_mod, y * r_mod

    def gray_matter_contour(theta_val):
        x = 0.8 * np.cos(theta_val)
        y = 0.5 * np.sin(theta_val)
        horn_ant = 0.45 * np.exp(-((theta_val - np.pi / 4) ** 2) / 0.05) + 0.45 * np.exp(
            -((theta_val - 3 * np.pi / 4) ** 2) / 0.05
        )
        horn_post = 0.25 * np.exp(-((theta_val - 5 * np.pi / 4) ** 2) / 0.1) + 0.25 * np.exp(
            -((theta_val - 7 * np.pi / 4) ** 2) / 0.1
        )
        r_mod = 0.6 + horn_ant + horn_post
        return x * r_mod, y * r_mod

    x_base, y_base = anatomical_contour(th)
    r_scale = (1.0 - (mscc_vals / 100.0) * 0.7).reshape(-1, 1)
    x_out, y_out = x_base * r_scale, y_base * r_scale
    inner_scale = np.sqrt(np.clip(ratios, 0.0, 1.0)).reshape(-1, 1)
    x_in, y_in = x_out * inner_scale, y_out * inner_scale

    out_colors = np.zeros((num_z, num_theta, 4))
    out_colors[:, :, :] = [0.88, 0.72, 0.78, 0.55]
    cmap = plt.get_cmap("Reds")
    in_colors = np.zeros((num_z, num_theta, 4))
    for i in range(num_z):
        c = cmap(0.4 + float(ratios[i]) * 0.6)
        in_colors[i, :, :] = c
        in_colors[i, :, 3] = 0.0 if ratios[i] < 0.01 else 0.85

    fig = plt.figure(figsize=(10, 16), facecolor="white")
    ax = fig.add_subplot(111, projection="3d")
    ls = LightSource(azdeg=165, altdeg=45)
    ax.plot_surface(x_out, y_out, z, facecolors=out_colors, antialiased=True, rstride=1, cstride=1, linewidth=0, shade=True, lightsource=ls)
    ax.plot_surface(x_in, y_in, z, facecolors=in_colors, antialiased=True, rstride=1, cstride=1, linewidth=0, shade=True, lightsource=ls)

    for z_idx, z_val in [(0, z_phys[0]), (-1, z_phys[-1])]:
        rs = r_scale[z_idx, 0]
        xg, yg = gray_matter_contour(theta)
        verts = [list(zip(xg * rs, yg * rs, [z_val] * len(xg)))]
        ax.add_collection3d(Poly3DCollection(verts, color="#AAAAAA", alpha=0.8))
        ax.plot(xg * rs, yg * rs, z_val, color="#888888", linewidth=1.2)

    last_seg = ""
    for i, seg in enumerate(segments):
        if seg != last_seg:
            last_seg = seg
            z_val = z_phys[i]
            xb, yb = anatomical_contour(theta)
            rs = r_scale[i, 0]
            ax.plot(xb * rs * 1.05, yb * rs * 1.05, z_val, color="#222222", linewidth=1.5, alpha=0.5)
            level_name = seg.split("-")[0]
            if level_name:
                z_pos = (z_val - 20) * 1.1 + 20 - 7.2
                ax.text(-5.8, 0, z_pos, level_name, color="#222222", fontsize=13, fontweight="bold", va="center", ha="right")

    z_last = z_phys[-1]
    xb, yb = anatomical_contour(theta)
    rs_last = r_scale[-1, 0]
    ax.plot(xb * rs_last * 1.05, yb * rs_last * 1.05, z_last, color="#222222", linewidth=1.5, alpha=0.5)
    last_level = segments[-1].split("-")[1]
    if last_level:
        z_pos_last = (z_last - 20) * 1.1 + 20 - 7.2
        ax.text(-5.8, 0, z_pos_last, last_level, color="#222222", fontsize=13, fontweight="bold", va="center", ha="right")

    ax.set_box_aspect((1, 1, 3))
    ax.view_init(elev=22, azim=35)
    ax.set_axis_off()
    plt.title(f"3D Anatomical Analysis: {subject_id}\nStructural Compression + Lesion Core", fontsize=16, fontweight="bold", color="#2C3E50")
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()
    logging.info("Written: %s", output_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create 3D SCI+MSCC visualization per subject.")
    parser.add_argument("--base_dir", type=Path, required=True, help="Directory containing subject subfolders")
    parser.add_argument("--output_name", default="spine_biomarker_3d.png", help="Output PNG name inside each subject directory")
    return parser.parse_args()


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
    args = parse_args()
    subject_ids = sorted([d for d in os.listdir(args.base_dir) if os.path.isdir(args.base_dir / d)])
    logging.info("Found %s subjects", len(subject_ids))
    for subject_id in subject_ids:
        subject_path = args.base_dir / subject_id
        try:
            create_3d_visualization(subject_path, subject_path / args.output_name, subject_id)
        except Exception as e:
            logging.exception("Failed %s: %s", subject_id, e)


if __name__ == "__main__":
    main()
